package findTheDifferent;

import java.util.Arrays;

/**
 * 
 * @author reggie
 *
 */
public class Demo {
	/**
	 * Given two strings s and t which consist of only lowercase letters.
	 * 
	 * String t is generated by random shuffling string s and then add one more
	 * letter at a random position.
	 * 
	 * Find the letter that was added in t.
	 * 
	 * @param s
	 * @param t
	 * @return
	 */
	public char findTheDifference(String s, String t) {
		char[] charS = s.toCharArray();
		char[] charT = t.toCharArray();
		Arrays.sort(charS);
		Arrays.sort(charT);
		for (int i = 0; i < charS.length; i++) {
			if (charS[i] != charT[i])
				return charT[i];
		}
		return charT[charT.length - 1];
	}
}
